# Site settings
title: Amis des Musées d'Art de Rouen
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://amis-musees-rouen.fr" # the base hostname & protocol for your site
permalink: /:title.html

# Default Layout
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

# Sitemap.xml
sitemap:
    file: "/sitemap.xml"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "laquo", "raquo"] # http://stackoverflow.com/questions/25596792/how-do-i-turn-off-smart-quotes-in-jekyll#25597026

# Prose.io
prose:
  ignore:
    - _config.yml
    - 404.html
    - main.css
    - google-analytics.js
    - CNAME
    - README.md
    - .gitignore
    - .jekyll-metadata
    - /_layouts
    - /_plugins
    - Gemfile
    - Gemfile.lock
    - /fonts
  media: "fichiers"
